// Superfluidity.js
(function($){
Type.registerNamespace('Superfluidity');Superfluidity.KeyCodes=function(){};Superfluidity.KeyCodes.prototype = {backspace:8,tab:9,enter:13,shift:16,ctrl:17,alt:18,pause_break:19,caps_lock:20,escape:27,space:32,page_up:33,page_down:34,end:35,home:36,left_arrow:37,up_arrow:38,right_arrow:39,down_arrow:40,insert:45,delete_key:46,d0:48,d1:49,d2:50,d3:51,d4:52,d5:53,d6:54,d7:55,d8:56,d9:57,a:65,b:66,c:67,d:68,e:69,f:70,g:71,h:72,i:73,j:74,k:75,l:76,m:77,n:78,o:79,p:80,q:81,r:82,s:83,t:84,u:85,v:86,w:87,x:88,y:89,z:90,left_window_key:91,right_window_key:92,select_key:93,numpad_0:96,numpad_1:97,numpad_2:98,numpad_3:99,numpad_4:100,numpad_5:101,numpad_6:102,numpad_7:103,numpad_8:104,numpad_9:105,multiply:106,add:107,subtract:109,decimal_point:110,divide:111,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123,num_lock:144,scroll_lock:145,semi_colon:186,equal_sign:187,comma:188,dash:189,period:190,forward_slash:191,grave_accent:192,open_bracket:219,back_slash:220,close_braket:221,single_quote:222}
Superfluidity.KeyCodes.registerEnum('Superfluidity.KeyCodes',false);window.$0=function(){var $0=new Superfluidity.Player(new Superfluidity.Vector(0,0),45);Superfluidity.World.$0();Superfluidity.Renderer.instance=new Superfluidity.Renderer();Superfluidity.Renderer.instance.renderWorld($0);}
Superfluidity.Player=function(position,directionAngle){this.directionAngle=directionAngle;var $0=directionAngle*Math.PI/180;this.position=position;this.directionVector=new Superfluidity.Vector(Math.cos($0),Math.sin($0));this.$6();}
Superfluidity.Player.prototype={position:null,directionAngle:0,directionVector:null,$0:function($p0,$p1){this.position.x=$p0;this.position.y=$p1;Superfluidity.Renderer.instance.renderWorld(this);},$1:function($p0){this.directionAngle=$p0;var $0=$p0*Math.PI/180;this.directionVector.x=Math.cos($0);this.directionVector.y=Math.sin($0);Superfluidity.Renderer.instance.renderWorld(this);},$2:function(){this.position.x=this.position.x+this.directionVector.x*0.1;this.position.y=this.position.y+this.directionVector.y*0.1;},$3:function(){this.position.x=this.position.x-this.directionVector.x*0.1;this.position.y=this.position.y-this.directionVector.y*0.1;},$4:function(){this.$1(this.directionAngle+3);},$5:function(){this.$1(this.directionAngle-3);},$6:function(){$(document).keydown(null,ss.Delegate.create(this,function($p1_0){
switch($p1_0.which){case 38:case 87:this.$2();break;case 40:case 83:this.$3();break;case 39:case 68:this.$5();break;case 37:case 65:this.$4();break;}Superfluidity.Renderer.instance.renderWorld(this);}));},canSee:function(tile){return Math.abs(Superfluidity.Vector.smallerAngleBetween(Superfluidity.Vector.subtract(tile.getCorner1(),this.position),this.directionVector))<45||Math.abs(Superfluidity.Vector.smallerAngleBetween(Superfluidity.Vector.subtract(tile.getCorner2(),this.position),this.directionVector))<45||Math.abs(Superfluidity.Vector.smallerAngleBetween(Superfluidity.Vector.subtract(tile.getCorner3(),this.position),this.directionVector))<45||Math.abs(Superfluidity.Vector.smallerAngleBetween(Superfluidity.Vector.subtract(tile.getCorner4(),this.position),this.directionVector))<45;}}
Superfluidity.Renderer=function(){var $0=document.getElementById('canvas');this.$0=$0.getContext('2d');}
Superfluidity.Renderer.prototype={$0:null,renderWorld:function(player){this.$4();for(var $0=0;$0<Superfluidity.World.tiles.length;$0++){var $1=Superfluidity.World.tiles[$0];if(player.canSee($1)){var $2=this.convertToViewportPoint($1.getCorner1(),player);var $3=this.convertToViewportPoint($1.getCorner2(),player);var $4=this.convertToViewportPoint($1.getCorner3(),player);var $5=this.convertToViewportPoint($1.getCorner4(),player);this.$3($2,$3,$4,$5);}}},convertToViewportPoint:function(point,player){var $0=new Superfluidity.Vector(point.x-player.position.x,point.y-player.position.y);var $1=this.$1($0,player);var $2=this.$2($0,player);return new Superfluidity.Vector($1*429,$2*429);},$1:function($p0,$p1){var $0=($p0.abs()*$p1.directionVector.abs())/Superfluidity.Vector.dot($p0,$p1.directionVector);var $1=Math.sqrt(Math.abs(($0*$0)-1));var $2=Superfluidity.Vector.smallerAngleBetween($p1.directionVector,$p0);if($2>0){return 0.7+$1;}else{return 0.7-$1;}},$2:function($p0,$p1){var $0=$p0.abs();var $1=1.4-((($0-1)/$0)-0.3);return $1;},$3:function($p0,$p1,$p2,$p3){this.$0.fillStyle='#0f0';this.$0.beginPath();this.$0.moveTo($p0.x,$p0.y);this.$0.lineTo($p1.x,$p1.y);this.$0.lineTo($p2.x,$p2.y);this.$0.lineTo($p3.x,$p3.y);this.$0.lineTo($p0.x,$p0.y);this.$0.fill();this.$0.closePath();},$4:function(){this.$0.clearRect(0,0,600,600);}}
Superfluidity.Szuperosztaly=function(){}
Superfluidity.Szuperosztaly.prototype={publikusMezoMertScriptSharpbanNincsPropertySajna:0,ezaztanszuperosztaly:function(){this.publikusMezoMertScriptSharpbanNincsPropertySajna=42;}}
Superfluidity.Tile=function(x,y,width,height){this.$0=new Superfluidity.Vector(x,y);this.$1=new Superfluidity.Vector(x,y+height);this.$2=new Superfluidity.Vector(x+width,y+height);this.$3=new Superfluidity.Vector(x+width,y);}
Superfluidity.Tile.prototype={$0:null,$1:null,$2:null,$3:null,getCorner1:function(){return this.$0;},getCorner2:function(){return this.$1;},getCorner3:function(){return this.$2;},getCorner4:function(){return this.$3;}}
Superfluidity.Vector=function(x,y){this.x=x;this.y=y;}
Superfluidity.Vector.dot=function(v1,v2){return v1.x*v2.x+v1.y*v2.y;}
Superfluidity.Vector.smallerAngleBetween=function(v1,v2){var $0=v1.angle()-v2.angle();if($0<-180){return $0+360;}else if($0>180){return $0-360;}else{return $0;}}
Superfluidity.Vector.subtract=function(v1,v2){return new Superfluidity.Vector(v1.x-v2.x,v1.y-v2.y);}
Superfluidity.Vector.prototype={x:0,y:0,abs:function(){return Math.sqrt(this.x*this.x+this.y*this.y);},angle:function(){var $0=45/Math.atan(1);var $1=($0*Math.atan2(this.y,this.x));if($1>=0){return $1;}return 360+$1;},alert:function(name){alert('A '+name+' vektor: '+this.x+', '+this.y);}}
Superfluidity.World=function(){}
Superfluidity.World.$0=function(){var $0=true;var $1=0;Superfluidity.World.tiles=new Array(45);for(var $2=-10;$2<10;$2++){for(var $3=-10;$3<9;$3++){if($0){var $4=new Superfluidity.Tile($2,$3,1,1);Superfluidity.World.tiles[$1++]=$4;}$0=!$0;}}}
Superfluidity.Class1=function(){}
Superfluidity.Player.registerClass('Superfluidity.Player');Superfluidity.Renderer.registerClass('Superfluidity.Renderer');Superfluidity.Szuperosztaly.registerClass('Superfluidity.Szuperosztaly');Superfluidity.Tile.registerClass('Superfluidity.Tile');Superfluidity.Vector.registerClass('Superfluidity.Vector');Superfluidity.World.registerClass('Superfluidity.World');Superfluidity.Class1.registerClass('Superfluidity.Class1');(function(){$(function(){
$0();});})();
Superfluidity.Renderer.instance=null;Superfluidity.World.tiles=null;})(jQuery);// This script was generated using Script# v0.7.3.0
